# Generated by Django 5.0.2 on 2024-02-07 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Employee Name', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Phone', 'Phone'), ('Computer Accessories', 'Computer Accessories'), ('Stationery', 'Stationery'), ('Printing Accessories', 'Printing Accessories'), ('Safety Accessories', 'Safety Accessories'), ('Others', 'Others')], max_length=20, null=True)),
                ('assign_date', models.DateTimeField(blank=True, null=True)),
                ('assign_time', models.TimeField(blank=True, default='Not Mentioned', null=True)),
                ('initial_condition', models.CharField(blank=True, choices=[('No Damage', 'No Damage'), ('Partially Damage', 'Partially Damage'), ('Damage', 'Damage'), ('Others', 'Others')], max_length=20, null=True)),
                ('initial_condition_log', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, default='Not Mentioned', null=True)),
                ('return_condition', models.CharField(blank=True, choices=[('No Damage', 'No Damage'), ('Partially Damage', 'Partially Damage'), ('Damage', 'Damage'), ('Others', 'Others')], max_length=20, null=True)),
                ('return_condition_log', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.employeeinformation')),
            ],
        ),
    ]
