# Generated by Django 5.0.2 on 2024-02-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_companyinformation_alter_assettrack_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettrack',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Returned', 'Returned'), ('No Return', 'No Return')], default='Pending', max_length=20, null=True),
        ),
    ]
