# Generated by Django 5.0.2 on 2024-02-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_assettrack_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='name',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
