# Generated by Django 5.0.2 on 2024-02-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_companyinformation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettrack',
            name='assign_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assettrack',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
